on:
  push:
    branches:
      - "main"
jobs:
  build_and_push:
    strategy:
      matrix:
        cdktf: [0.10.3]
        tf: [1.1.9]
        node: [16.15.0]
        os: [alpine3.14, alpine3.15]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            cdktf_version=${{ matrix.cdktf }}
            tf_version=${{ matrix.tf }}
            node_version=${{ matrix.node }}
            os_version=${{ matrix.os }}
            build_system=github
            build_number=$GITHUB_RUN_NUMBER
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cdktf:${{ matrix.cdktf }}-tf${{ matrix.tf }}-node${{ matrix.node }}-${{ matrix.os }}
